# Generated by Django 4.2.27 on 2025-12-20 01:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_safra', models.CharField(help_text='Ex: 2024/2025, Safra Verão 2024', max_length=50, verbose_name='Nome da Safra')),
                ('cultura', models.CharField(help_text='Ex: Soja, Milho, Trigo', max_length=100, verbose_name='Cultura')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Em Planejamento'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJAMENTO', max_length=20, verbose_name='Status')),
                ('producao_estimada_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Produção Estimada (kg)')),
                ('producao_real_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Produção Real (kg)')),
                ('preco_venda_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Preço de Venda (R$/kg)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Ciclo de Produção',
                'verbose_name_plural': 'Ciclos de Produção',
                'db_table': 'ciclos_producao',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('codigo', models.CharField(blank=True, help_text='Código interno ou NCM', max_length=50, null=True, verbose_name='Código')),
                ('categoria', models.CharField(choices=[('SEMENTE', 'Semente'), ('FERTILIZANTE', 'Fertilizante'), ('DEFENSIVO', 'Defensivo Agrícola'), ('HERBICIDA', 'Herbicida'), ('FUNGICIDA', 'Fungicida'), ('INSETICIDA', 'Inseticida'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria')),
                ('unidade', models.CharField(default='KG', help_text='Ex: KG, L, UN, SC', max_length=20, verbose_name='Unidade de Medida')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Talhão')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('coordenadas_json', models.TextField(blank=True, help_text='Array de coordenadas lat/lng do polígono no formato JSON', null=True, verbose_name='Coordenadas (JSON)')),
                ('area_hectares', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Área (hectares)')),
                ('cultura_atual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultura Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
                'db_table': 'talhoes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('PLANTIO', 'Plantio'), ('ADUBACAO', 'Adubação'), ('PULVERIZACAO', 'Pulverização'), ('COLHEITA', 'Colheita'), ('IRRIGACAO', 'Irrigação'), ('PREPARO_SOLO', 'Preparo do Solo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Operação')),
                ('quantidade_aplicada', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade Aplicada')),
                ('data_operacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Operação')),
                ('area_aplicada_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Se diferente da área total do talhão', max_digits=10, null=True, verbose_name='Área Aplicada (ha)')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='core.cicloproducao', verbose_name='Ciclo de Produção')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='core.produto', verbose_name='Produto/Insumo')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='core.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Operação de Campo',
                'verbose_name_plural': 'Operações de Campo',
                'db_table': 'operacoes_campo',
                'ordering': ['-data_operacao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Unitário')),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('chave_nfe', models.CharField(blank=True, help_text='Chave de acesso da Nota Fiscal Eletrônica (44 dígitos)', max_length=44, null=True, verbose_name='Chave NFe')),
                ('numero_nfe', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da NFe')),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'movimentacoes_estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddField(
            model_name='cicloproducao',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='core.talhao', verbose_name='Talhão'),
        ),
    ]
