# Generated by Django 4.2.27 on 2025-12-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimentacaoestoque_operacao_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cicloproducao',
            name='preco_venda_kg',
        ),
        migrations.RemoveField(
            model_name='cicloproducao',
            name='producao_estimada_kg',
        ),
        migrations.RemoveField(
            model_name='cicloproducao',
            name='producao_real_kg',
        ),
        migrations.AddField(
            model_name='cicloproducao',
            name='preco_venda_saca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda (R$/sc)'),
        ),
        migrations.AddField(
            model_name='cicloproducao',
            name='producao_estimada_saca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Produção Estimada (sc)'),
        ),
        migrations.AddField(
            model_name='cicloproducao',
            name='producao_real_saca',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Produção Real (sc)'),
        ),
    ]
