# Generated by Django 4.2.27 on 2025-12-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_userprofile_cicloproducao_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(default='HK Talhões', max_length=100, verbose_name='Nome do Sistema')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Link para Logo (URL)')),
                ('cor_primaria', models.CharField(default='#212529', max_length=20, verbose_name='Cor Primária (Hex)')),
                ('mensagem_dashboard', models.TextField(blank=True, null=True, verbose_name='Mensagem de Boas-vindas (Dashboard)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'configuracao_sistema',
            },
        ),
    ]
