# Generated by Django 4.2.27 on 2025-12-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracaosistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo do Sistema'),
        ),
    ]
