# Generated by Django 4.2.27 on 2025-12-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fazenda_talhao_fazenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, este talhão é uma subdivisão do pai.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtalhoes', to='core.talhao', verbose_name='Talhão Pai'),
        ),
    ]
