# Generated by Django 4.2.27 on 2025-12-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fazenda_latitude_fazenda_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaTalhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp. Máxima (°C)')),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp. Mínima (°C)')),
                ('precipitacao', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precipitação (mm)')),
                ('umidade_relativa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Umidade Relativa (%)')),
                ('velocidade_vento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidade Vento (km/h)')),
                ('fonte', models.CharField(choices=[('API', 'Automático (API)'), ('MANUAL', 'Manual')], default='API', max_length=20, verbose_name='Fonte dos Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_climaticos', to='core.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Dado Climático',
                'verbose_name_plural': 'Dados Climáticos',
                'db_table': 'clima_talhao',
                'ordering': ['-data'],
                'unique_together': {('talhao', 'data')},
            },
        ),
    ]
