# Generated by Django 4.2.27 on 2025-12-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_climafazenda_delete_climatalhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocampo',
            name='categoria',
            field=models.CharField(choices=[('INSUMO', 'Insumo/Produto'), ('MAO_DE_OBRA', 'Mão de Obra'), ('SERVICO', 'Serviço')], default='INSUMO', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='operacaocampo',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição (Mão de Obra/Serviço)'),
        ),
        migrations.AddField(
            model_name='operacaocampo',
            name='maquinario_terceiro',
            field=models.BooleanField(default=False, verbose_name='Maquinário de Terceiro'),
        ),
        migrations.AddField(
            model_name='operacaocampo',
            name='unidade_custo',
            field=models.CharField(choices=[('BRL', 'Reais (R$)'), ('SACA', 'Sacas')], default='BRL', max_length=10, verbose_name='Unidade do Custo'),
        ),
        migrations.AlterField(
            model_name='operacaocampo',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='core.produto', verbose_name='Produto/Insumo'),
        ),
        migrations.AlterField(
            model_name='operacaocampo',
            name='quantidade_aplicada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade Aplicada'),
        ),
    ]
