# Generated by Django 4.2.27 on 2025-12-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_operacaocampo_categoria_operacaocampo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocampo',
            name='custo_operacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo da Operação'),
        ),
    ]
