# Generated by Django 4.2.27 on 2025-12-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_operacaocampo_custo_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor')),
                ('quantidade_contratada', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade Contratada')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário (R$)')),
                ('data_contrato', models.DateField(verbose_name='Data do Contrato')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('arquivo_contrato', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Arquivo do Contrato (PDF/Img)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Contrato de Compra',
                'verbose_name_plural': 'Contratos de Compra',
                'db_table': 'contratos_compra',
                'ordering': ['-data_contrato'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='core.contratocompra', verbose_name='Contrato de Compra'),
        ),
    ]
