# Generated by Django 4.2.27 on 2025-12-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contratocompra_movimentacaoestoque_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qtd. Solicitada')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcialmente Atendido'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status Item')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'itens_pedido_compra',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor')),
                ('data_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='pedidos/', verbose_name='Arquivo/Contrato')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcialmente Atendido'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status Geral')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'db_table': 'pedidos_compra',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='contrato',
        ),
        migrations.DeleteModel(
            name='ContratoCompra',
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedidocompra'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='item_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='core.itempedidocompra', verbose_name='Item do Pedido de Compra'),
        ),
    ]
