# Generated by Django 4.2.27 on 2025-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itempedidocompra_pedidocompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='arquivo_nfe',
            field=models.FileField(blank=True, null=True, upload_to='nfe_arquivos/', verbose_name='Arquivo NFe/XML'),
        ),
    ]
