# Generated by Django 4.2.27 on 2025-12-27 00:24

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_movimentacaoestoque_arquivo_nfe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CicloProducao',
            new_name='Plantio',
        ),
        migrations.AlterModelTable(
            name='plantio',
            table='plantios',
        ),
        migrations.AlterModelOptions(
            name='plantio',
            options={'ordering': ['-data_plantio'], 'verbose_name': 'Plantio', 'verbose_name_plural': 'Plantios'},
        ),
        migrations.RenameField(
            model_name='plantio',
            old_name='data_inicio',
            new_name='data_plantio',
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Safra (Ex: 23/24)')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('ativa', models.BooleanField(default=True, verbose_name='Safra Atual?')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Safra',
                'verbose_name_plural': 'Safras',
                'db_table': 'safras',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='plantio',
            name='safra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='core.safra', verbose_name='Safra'),
        ),
        migrations.RemoveField(
            model_name='plantio',
            name='nome_safra',
        ),
        migrations.CreateModel(
            name='TabelaClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Tabela')),
                ('cultura', models.CharField(max_length=50, verbose_name='Cultura')),
                ('padrao_umidade', models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='Padrão Umidade (%)')),
                ('padrao_impureza', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Padrão Impureza (%)')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tabela de Classificação',
                'verbose_name_plural': 'Tabelas de Classificação',
                'db_table': 'tabelas_classificacao',
            },
        ),
        migrations.CreateModel(
            name='Romaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('numero_ticket', models.CharField(max_length=50, verbose_name='Nº Ticket/Romaneio')),
                ('motorista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motorista')),
                ('placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa')),
                ('peso_tara', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Peso Tara (kg)')),
                ('peso_bruto', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Peso Bruto (kg)')),
                ('umidade_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Umidade (%)')),
                ('impureza_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impureza (%)')),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Peso Líquido (kg)')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda', verbose_name='Fazenda')),
                ('plantio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plantio', verbose_name='Plantio/Safra')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Romaneio',
                'verbose_name_plural': 'Romaneios',
                'db_table': 'romaneios',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RateioCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Rateio')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total a Ratear')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Custo (Ex: Energia)')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Rateio de Custo',
                'verbose_name_plural': 'Rateios de Custo',
                'db_table': 'rateios_custo',
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto (Soja/Milho)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('fonte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'db_table': 'cotacoes',
                'ordering': ['-data'],
                'unique_together': {('data', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='ContratoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente/Comprador')),
                ('quantidade_sacas', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade (sc)')),
                ('valor_saca', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Saca (R$)')),
                ('data_entrega', models.DateField(verbose_name='Data Entrega/Vencimento')),
                ('tipo', models.CharField(choices=[('FUTURO', 'Mercado Futuro'), ('SPOT', 'Mercado Spot (Disponível)')], default='SPOT', max_length=20, verbose_name='Tipo de Venda')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contrato de Venda',
                'verbose_name_plural': 'Contratos de Venda',
                'db_table': 'contratos_venda',
            },
        ),
        migrations.AddField(
            model_name='talhao',
            name='tipo_solo',
            field=models.CharField(blank=True, choices=[('ARGILOSO', 'Argiloso'), ('ARENOSO', 'Arenoso'), ('MISTO', 'Misto'), ('HUMIFERO', 'Humífero')], max_length=50, null=True, verbose_name='Tipo de Solo'),
        ),
    ]
