# Generated by Django 4.2.27 on 2025-12-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_plantio_talhao_tipo_solo_tabelaclassificacao_safra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='data_colheita_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Colheita'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='data_plantio',
            field=models.DateField(verbose_name='Data de Plantio'),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='core.talhao', verbose_name='Talhão'),
        ),
    ]
