# Generated by Django 4.2.27 on 2025-12-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_plantio_data_colheita_prevista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocampo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado/Realizado'), ('CANCELADO', 'Cancelado')], default='APROVADO', max_length=20, verbose_name='Status da Requisição'),
        ),
    ]
