# Generated by Django 4.2.27 on 2025-12-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_operacaocampo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateiocusto',
            name='criterio',
            field=models.CharField(choices=[('AREA', 'Proporcional à Área (ha)'), ('IGUAL', 'Divisão Igualitária entre Talhões')], default='AREA', max_length=20, verbose_name='Critério de Rateio'),
        ),
        migrations.AddField(
            model_name='rateiocusto',
            name='safra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.safra', verbose_name='Safra de Referência'),
        ),
        migrations.AlterField(
            model_name='rateiocusto',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição do Custo (Ex: Energia, Adm)'),
        ),
    ]
