# Generated by Django 4.2.27 on 2025-12-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rateiocusto_criterio_rateiocusto_safra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaclassificacao',
            name='taxa_secagem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa Secagem Extra (%)'),
        ),
    ]
