# Generated by Django 4.2.27 on 2025-12-27 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tabelaclassificacao_taxa_secagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fixacao', models.DateField(verbose_name='Data da Fixação')),
                ('quantidade_sacas', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade Fixada (sc)')),
                ('valor_saca', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço na Fixação (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Valor Total (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixacoes', to='core.contratovenda', verbose_name='Contrato')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixacoes', to='core.romaneio', verbose_name='Romaneio')),
            ],
            options={
                'verbose_name': 'Fixação de Preço',
                'verbose_name_plural': 'Fixações',
                'db_table': 'fixacoes',
            },
        ),
    ]
