# Generated by Django 4.2.27 on 2025-12-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fixacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='romaneio',
            name='peso_quebra_tecnica',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Quebra Técnica (kg)'),
        ),
        migrations.CreateModel(
            name='TaxaArmazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Armazém/Fornecedor')),
                ('taxa_recepcao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Recepção (R$/Ton)')),
                ('taxa_armazenagem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Armazenagem (R$/Ton/Quinzena)')),
                ('quebra_tecnica', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Quebra Técnica (%)')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Taxa de Armazém',
                'verbose_name_plural': 'Taxas de Armazém',
                'db_table': 'taxas_armazem',
                'unique_together': {('empresa', 'fornecedor')},
            },
        ),
        migrations.AddField(
            model_name='romaneio',
            name='armazem_terceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taxaarmazem', verbose_name='Armazém (Terceiro)'),
        ),
    ]
