# Generated by Django 4.2.27 on 2025-12-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_fornecedor_cliente_alter_contratovenda_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='nome_sistema',
            field=models.CharField(default='Agro Gestor PV', max_length=100, verbose_name='Nome do Sistema'),
        ),
        migrations.CreateModel(
            name='ItemContratoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.contratovenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Contrato',
                'verbose_name_plural': 'Itens do Contrato',
                'db_table': 'itens_contrato_venda',
            },
        ),
    ]
