# Generated by Django 4.2.27 on 2025-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_configuracaosistema_nome_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('SEMENTE', 'Semente'), ('FERTILIZANTE', 'Fertilizante'), ('DEFENSIVO', 'Defensivo Agrícola'), ('HERBICIDA', 'Herbicida'), ('FUNGICIDA', 'Fungicida'), ('INSETICIDA', 'Inseticida'), ('GRAO', 'Grão (Produção)'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
    ]
