# Generated by Django 4.2.27 on 2025-12-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratovenda',
            name='unidade',
            field=models.CharField(choices=[('SC', 'Sacas (60kg)'), ('KG', 'Quilogramas'), ('TON', 'Toneladas')], default='SC', max_length=3, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='itemcontratovenda',
            name='unidade',
            field=models.CharField(choices=[('SC', 'Sacas'), ('KG', 'Kg'), ('TON', 'Ton')], default='SC', max_length=3, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='contratovenda',
            name='quantidade_sacas',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='contratovenda',
            name='valor_saca',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)'),
        ),
    ]
