# Generated by Django 4.2.27 on 2025-12-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contratovenda_unidade_itemcontratovenda_unidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixacao',
            old_name='valor_saca',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='contratovenda',
            name='quantidade_sacas',
        ),
        migrations.RemoveField(
            model_name='contratovenda',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='contratovenda',
            name='valor_saca',
        ),
        migrations.RemoveField(
            model_name='fixacao',
            name='quantidade_sacas',
        ),
        migrations.AddField(
            model_name='fixacao',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixacoes', to='core.itemcontratovenda', verbose_name='Item do Contrato'),
        ),
        migrations.AddField(
            model_name='fixacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, verbose_name='Quantidade Fixada'),
            preserve_default=False,
        ),
    ]
