# Generated by Django 4.2.27 on 2025-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_valor_saca_fixacao_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontratovenda',
            name='unidade',
            field=models.CharField(choices=[('SC', 'Sacas (60kg)'), ('KG', 'Quilogramas (Granel)'), ('TON', 'Toneladas (Granel)')], default='SC', max_length=3, verbose_name='Unidade'),
        ),
    ]
