# Generated by Django 4.2.27 on 2025-12-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_itemcontratovenda_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcontratovenda',
            name='unidade',
            field=models.CharField(choices=[('SC', 'Sacas (60kg)'), ('SC50', 'Sacas (50kg)'), ('SC40', 'Sacas (40kg)'), ('SC25', 'Sacas (25kg)'), ('KG', 'Quilogramas (Granel)'), ('TON', 'Toneladas (Granel)')], default='SC', max_length=5, verbose_name='Unidade'),
        ),
    ]
