# Generated by Django 4.2.27 on 2025-12-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_itemcontratovenda_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontratovenda',
            name='fazenda',
            field=models.ForeignKey(blank=True, help_text='Informe se este item sair de uma fazenda específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fazenda', verbose_name='Fazenda (Opcional)'),
        ),
    ]
