# Generated by Django 4.2.27 on 2025-12-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_itemcontratovenda_fazenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxaarmazem',
            name='frequencia',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='QUINZENAL', max_length=20, verbose_name='Frequência'),
        ),
        migrations.AddField(
            model_name='taxaarmazem',
            name='unidade',
            field=models.CharField(choices=[('BRL', 'Reais (R$)'), ('SACA', 'Saca')], default='BRL', max_length=20, verbose_name='Unidade de Pagamento'),
        ),
        migrations.AlterField(
            model_name='taxaarmazem',
            name='taxa_armazenagem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Armazenagem'),
        ),
    ]
