# Generated by Django 4.2.27 on 2025-12-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_taxaarmazem_frequencia_taxaarmazem_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='romaneio',
            name='avariado_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avariado (%)'),
        ),
        migrations.AddField(
            model_name='romaneio',
            name='desconto_kg_avariado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desc. Avariado (kg)'),
        ),
        migrations.AddField(
            model_name='romaneio',
            name='desconto_kg_impureza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desc. Impureza (kg)'),
        ),
        migrations.AddField(
            model_name='romaneio',
            name='desconto_kg_umidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desc. Umidade (kg)'),
        ),
        migrations.AddField(
            model_name='romaneio',
            name='total_descontos_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descontos (kg)'),
        ),
        migrations.AddField(
            model_name='tabelaclassificacao',
            name='padrao_avariado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Padrão Avariado (%)'),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Líquido/Armazém (kg)'),
        ),
    ]
