# Generated by Django 4.2.27 on 2025-12-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_romaneio_avariado_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidocompra',
            name='fazenda',
            field=models.ForeignKey(blank=True, help_text='Informe se este item será destinado a uma fazenda específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fazenda', verbose_name='Fazenda (Opcional)'),
        ),
    ]
