# Generated by Django 4.2.27 on 2025-12-28 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_itempedidocompra_fazenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Proprietário'), ('MANAGER', 'Gerente'), ('OPERATOR', 'Operador')], default='OWNER', max_length=20, verbose_name='Função'),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Convidado')),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('MANAGER', 'Gerente'), ('OPERATOR', 'Operador')], default='OPERATOR', max_length=20, verbose_name='Função')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Convidado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Convite de Usuário',
                'verbose_name_plural': 'Convites de Usuários',
                'db_table': 'user_invitations',
            },
        ),
    ]
