# Generated by Django 4.2.27 on 2025-12-29 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_userprofile_role_userinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada/Receita'), ('SAIDA', 'Saída/Despesa')], max_length=10, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'db_table': 'categorias_financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Pago Parcial'), ('PAGO', 'Pago/Liquidado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'ENTRADA'}, on_delete=django.db.models.deletion.PROTECT, to='core.categoriafinanceira', verbose_name='Categoria/Plano de Contas')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='core.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fazenda', verbose_name='Fazenda Relacionada')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'db_table': 'contas_receber',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Pago Parcial'), ('PAGO', 'Pago/Liquidado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='financeiro/pagar/', verbose_name='Anexo (Boleto/NF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'SAIDA'}, on_delete=django.db.models.deletion.PROTECT, to='core.categoriafinanceira', verbose_name='Categoria/Plano de Contas')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fazenda', verbose_name='Fazenda Relacionada')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='core.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'db_table': 'contas_pagar',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='BaixaContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(verbose_name='Data do Recebimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Recebido')),
                ('metodo', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência/TED'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('CHEQUE', 'Cheque'), ('OUTROS', 'Outros')], default='TRANSFERENCIA', max_length=20, verbose_name='Método de Recebimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='core.contareceber')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Baixa de Conta a Receber',
                'verbose_name_plural': 'Baixas de Contas a Receber',
                'db_table': 'baixas_contas_receber',
            },
        ),
        migrations.CreateModel(
            name='BaixaContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago')),
                ('metodo', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência/TED'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('CHEQUE', 'Cheque'), ('OUTROS', 'Outros')], default='TRANSFERENCIA', max_length=20, verbose_name='Método de Pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='core.contapagar')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Baixa de Conta a Pagar',
                'verbose_name_plural': 'Baixas de Contas a Pagar',
                'db_table': 'baixas_contas_pagar',
            },
        ),
    ]
