# Generated by Django 4.2.27 on 2025-12-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_categoriafinanceira_contareceber_contapagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='movimentacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='core.movimentacaoestoque', verbose_name='Movimentação de Origem'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_nfe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº NFe'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='contrato_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='core.contratovenda', verbose_name='Contrato de Origem'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='fixacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='core.fixacao', verbose_name='Fixação de Origem'),
        ),
    ]
