# Generated by Django 4.2.27 on 2025-12-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_contapagar_movimentacao_origem_contapagar_numero_nfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='item_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='core.itemcontratovenda', verbose_name='Item do Contrato de Venda'),
        ),
    ]
