# Generated by Django 4.2.27 on 2025-12-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_movimentacaoestoque_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='numero_nfe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº NFe/Doc'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'SAIDA'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoriafinanceira', verbose_name='Categoria/Plano de Contas'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='categoria',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'ENTRADA'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoriafinanceira', verbose_name='Categoria/Plano de Contas'),
        ),
    ]
