# Generated by Django 4.2.27 on 2025-12-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_contareceber_numero_nfe_alter_contapagar_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='core.fazenda', verbose_name='Fazenda'),
        ),
    ]
