# Generated by Django 4.2.27 on 2025-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_movimentacaoestoque_fazenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantio',
            name='talhoes',
            field=models.ManyToManyField(blank=True, related_name='plantios_multi', to='core.talhao', verbose_name='Talhões'),
        ),
    ]
