# Generated by Django 4.2.27 on 2025-12-29 21:35

from django.db import migrations

def migrate_talhao_to_talhoes(apps, schema_editor):
    Plantio = apps.get_model('core', 'Plantio')
    for plantio in Plantio.objects.all():
        if plantio.talhao:
            plantio.talhoes.add(plantio.talhao)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_talhoes_m2m'),
    ]

    operations = [
        migrations.RunPython(migrate_talhao_to_talhoes),
    ]
