# Generated by Django 4.2.27 on 2025-12-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_migrate_talhoes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantio',
            name='talhao',
        ),
    ]
