# Generated by Django 4.2.27 on 2025-12-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_talhao_fk_from_plantio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantio',
            name='preco_venda_saca',
        ),
        migrations.RemoveField(
            model_name='plantio',
            name='producao_estimada_saca',
        ),
        migrations.AddField(
            model_name='plantio',
            name='preco_venda_estimado_sc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda Estimado (R$/sc)'),
        ),
        migrations.AddField(
            model_name='plantio',
            name='producao_estimada_sc_ha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Produção Estimada (sc/ha)'),
        ),
    ]
