# Generated by Django 4.2.27 on 2025-12-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_plantio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocampo',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='core.safra', verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='operacaocampo',
            name='talhoes',
            field=models.ManyToManyField(blank=True, related_name='operacoes_multi', to='core.talhao', verbose_name='Talhões'),
        ),
        migrations.AlterField(
            model_name='operacaocampo',
            name='talhao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_legacy', to='core.talhao', verbose_name='Talhão (Legado)'),
        ),
    ]
