# Generated by Django 4.2.27 on 2025-12-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_operacaocampo_safra_operacaocampo_talhoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaocampo',
            name='tipo_operacao',
            field=models.CharField(blank=True, choices=[('PLANTIO', 'Plantio'), ('ADUBACAO', 'Adubação'), ('PULVERIZACAO', 'Pulverização'), ('COLHEITA', 'Colheita'), ('IRRIGACAO', 'Irrigação'), ('PREPARO_SOLO', 'Preparo do Solo'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, null=True, verbose_name='Tipo de Operação (Legado)'),
        ),
        migrations.CreateModel(
            name='AtividadeCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Atividade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Atividade de Campo',
                'verbose_name_plural': 'Atividades de Campo',
                'db_table': 'atividades_campo',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='operacaocampo',
            name='atividades',
            field=models.ManyToManyField(blank=True, related_name='operacoes', to='core.atividadecampo', verbose_name='Atividades Realizadas'),
        ),
    ]
