# Generated by Django 4.2.27 on 2025-12-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_operacaocampo_tipo_operacao_atividadecampo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacaocampo',
            name='atividades',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='custo_operacao',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='maquinario_terceiro',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='quantidade_aplicada',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='talhao',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='tipo_operacao',
        ),
        migrations.RemoveField(
            model_name='operacaocampo',
            name='unidade_custo',
        ),
        migrations.AddField(
            model_name='operacaocampo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operacaocampo',
            name='area_aplicada_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Área Aplicada (ha)'),
        ),
        migrations.AlterField(
            model_name='operacaocampo',
            name='talhoes',
            field=models.ManyToManyField(blank=True, related_name='operacoes_campo', to='core.talhao', verbose_name='Talhões'),
        ),
        migrations.CreateModel(
            name='OperacaoCampoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('INSUMO', 'Insumo/Produto'), ('MAO_DE_OBRA', 'Mão de Obra'), ('SERVICO', 'Serviço')], default='INSUMO', max_length=20, verbose_name='Categoria')),
                ('maquinario_terceiro', models.BooleanField(default=False, verbose_name='Maquinário de Terceiro')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição/Serviço')),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Quantidade')),
                ('is_quantidade_total', models.BooleanField(default=False, help_text='Se desmarcado, considera Qtd/ha', verbose_name='Qtd é Total?')),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Custo Unitário')),
                ('is_custo_total', models.BooleanField(default=False, help_text='Se desmarcado, considera Custo/ha', verbose_name='Custo é Total?')),
                ('unidade_custo', models.CharField(choices=[('BRL', 'Reais (R$)'), ('SACA', 'Sacas')], default='BRL', max_length=10, verbose_name='Unidade')),
                ('custo_final', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Final')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.atividadecampo', verbose_name='Atividade/Tipo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.operacaocampo', verbose_name='Operação')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_operacao', to='core.produto', verbose_name='Produto/Insumo')),
            ],
            options={
                'verbose_name': 'Item de Operação',
                'verbose_name_plural': 'Itens de Operação',
            },
        ),
    ]
