# Generated by Django 4.2.27 on 2026-01-02 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_remove_operacaocampo_atividades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlvoMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Alvo')),
                ('tipo', models.CharField(choices=[('PRAGA', 'Praga'), ('DOENCA', 'Doença'), ('DANINHA', 'Planta Daninha')], max_length=20, verbose_name='Tipo')),
                ('nivel_alerta', models.DecimalField(decimal_places=2, default=0, help_text='Limite de incidência para tomada de decisão', max_digits=5, verbose_name='Nível de Alerta (%)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='alvos/', verbose_name='Imagem de Referência')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Danos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Alvo de Monitoramento',
                'verbose_name_plural': 'Alvos de Monitoramento',
                'db_table': 'alvos_monitoramento',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Coleta')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='core.talhao', verbose_name='Talhão')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Monitoramento',
                'verbose_name_plural': 'Monitoramentos',
                'db_table': 'monitoramentos',
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.CreateModel(
            name='MonitoramentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Incidência (%)')),
                ('severidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Escala de dano: 1 (Leve) a 5 (Muito Forte)', verbose_name='Severidade (1-5)')),
                ('contagem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Contagem (por m² ou planta)')),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alvomonitoramento', verbose_name='Alvo')),
                ('monitoramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.monitoramento')),
            ],
            options={
                'verbose_name': 'Item de Monitoramento',
                'verbose_name_plural': 'Itens de Monitoramento',
                'db_table': 'monitoramento_itens',
            },
        ),
    ]
