# Generated by Django 4.2.27 on 2026-01-02 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alvomonitoramento_monitoramento_monitoramentoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoramento',
            name='talhao',
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoramentos', to='core.plantio', verbose_name='Ciclo de Produção'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoramentos', to='core.safra', verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='talhoes',
            field=models.ManyToManyField(blank=True, related_name='monitoramentos', to='core.talhao', verbose_name='Talhões'),
        ),
    ]
