# Generated by Django 4.2.27 on 2026-01-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_monitoramento_talhao_monitoramento_ciclo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='monitoramentos/', verbose_name='Foto da Inspeção'),
        ),
    ]
